### ISSUE TITLE
Github support

### ISSUE THREAD

**Issue by rpalcolea** [MatrixCrawler/grails-spring-security-oauth2#1]
Hi! I don't know if you're in the Grails Slack community.

I wanted to reach out because I created an extension of your plugin to use Github. https://github.com/rpalcolea/grails-spring-security-oauth2-github

Hope that's ok with you, I followed the way you coded the Google's one.

Roberto

**Comment by MatrixCrawler** [comment]
Hi,
no i am not (yet) in the Slack Community.

It's totally ok with me if people are creating mor extensions.
I added yours to the list of known extension in my readme

Regards
Johannes

**Comment by rpalcolea** [comment]
Great thanks, your plugin is very helpful for something we're doing 👍
